### ISSUE TITLE
Does Rack need to be a dependency?

### ISSUE THREAD

**Issue by ms-ati** [eval/envied#19]
It would be great to use ENVied in applications that aren't necessarily web-apps. Does Rack have to be a full-on dependency?

**Comment by mpalmer** [comment]
I noticed that a little while ago and took a look.  `Rack::Utils.parse_query` is called in the `to_hash` coercer extension.  So, as it currently stands, `rack` is a dependency.  `parse_query` could be reimplemented locally, though, and that would remove the dep.  On the other hand, apart from the extra disk space, depending on `rack` doesn't have any ill-effects.

**Comment by olleolleolle** [comment]
Does Rack have to be a `~>` dependency? If it were a `>=` dependency, it'd not break rack 2.x installs. 

(Rails 5 betas are rack ~> 2.x.)

**Comment by mpalmer** [comment]
Unless Rack has guaranteed that the API portions that ENVied depends on won't ever change, then yes, it does need to be a `~>` dependency, although if Rack 2.x hasn't changed the portions of the API, it could be a `< 3, >= 1.x` form instead of the short hand.

**Comment by javierjulio** [comment]
Great question. No, it does not. This is being worked on. You can find more info and code in #29 for what is coming up. I'm now working on Envied so expect releases soon. For now I just released v0.8.2 which includes Rails 5 support but we want to remove the rack dependency entirely since its not necessary. We can replace it with Ruby's `CGI.parse` which is in the stdlib.
