### ISSUE TITLE
Can I split the variables in multiple Envfiles?

### ISSUE THREAD

**Issue by attilastrba** [eval/envied#26]
Hi Guys,
I am trying to split up the local enviroment variables in a separate file so that I don't have to commit them in the GIT. So the Envfile would contain the CI variables, and once it detects that there is no CI running but it is a local usage than it would import the defaults from a different Envfile.

Is there a possibility to realise this in an easy way?
thanx.
Greetings
Attila

**Comment by javierjulio** [comment]
I'm not sure I follow because you should just be able to set variables in CI, for example, I use CircleCI and Travis and both allow you to set ENV variables through their configs or UI. You would just set the variables you want in your Envfile, whether required or with defaults and then just change the values for those necessary in your CI.
