### ISSUE TITLE
Change request: Do not coerce floats to integers

### ISSUE THREAD

**Issue by rhys-vdw** [eval/envied#31]
Currently this is acceptable:

```rb
variable :SOME_SETTING, :integer, default: 1
```

```
$ SOME_SETTING=0.01 ./bin/rails c
pry> ENVied.SOME_SETTING
=> 0
```

IMO this should raise a coercion error. I can't think of a situation where a user would knowingly enter a decimal where an integer is appropriate.

**Comment by javierjulio** [comment]
Good catch. There is a [simple coercer test](https://github.com/eval/envied/blob/master/spec/coercer_spec.rb#L22) but that's only assuming you give it an integer. We could add a test case for a decimal where it would be expected to throw an error or convert the value to an integer. There is an [error case test for integer coercion](https://github.com/eval/envied/blob/master/spec/envied_spec.rb#L103) but thats only if its just a string of text (non digits). Its clear we are missing some cases here.

**Comment by javierjulio** [comment]
Since we you are defining a variable as an integer (assume we did have a float type), wouldn't you still expect the coercion to convert it to an integer if you gave it a float? We could raise an error but I wonder if the desire is still that it converts it successfully. I've added your two issues to a proposal I've written on releases we could do for Envied. I'm hoping @eval will consider it and allow others contribute the effort of making and releasing those changes so he won't have to worry about dealing with it.

**Comment by rhys-vdw** [comment]
> wouldn't you still expect the coercion to convert it to an integer if you gave it a float?

I'm not sure why you would deliberately give a value that is of a different type to that required except by accident. In this case it might be because you misunderstood how the var was to be used. Coercion would be obscuring the error in this case. (Same reason you wouldn't coerce `http://www.google.com` into `0` for an integer column.)

**Comment by javierjulio** [comment]
We are tackling this in #35 ❤️
