### ISSUE TITLE
ideas on default-values

### ISSUE THREAD

**Issue by eval** [eval/envied#34]
The original idea behind default-values was to assist users/teammembers to quickly start using your project; an error with a long list of missing ENV-variables is not really welcoming.
Also, with default-values you give your users an example what would be an acceptable value.

The downside of default-values is that it's an abstraction that easily breaks: you might shield the user from having to worry about env-variables, but now the user might run into things like redis not running on the default-url you set etc. An error which is probably more cryptic and which requires the user to start looking where this value actually comes from.

The provided values only reach so far: giving variable `A` a default-value, results in `ENVied.A` having a value, not `ENV['A']` - so your application is using it, but the project's dependencies can't.

Another source of confusion with default-values is whether to provide the defined type, or a string (as is necessary when you disable defaults and have to use the ENV).

## sample-file

So, with the original motivation of 'easily bootstrap' in mind, how about another implementation, namely to generate an example file that can be sourced in the shell, e.g.:

```bash
# file: env.sample
export DATABASE_URL= # e.g. postgres://user:pw@localhost/database
export REDIS_URL=redis://localhost:6379
```

The following might be the Envfile that generated this:
```
variable :DATABASE_URL, :string, sample_desc: "e.g. postgres://user:pw@localhost/database"
variable :REDIS_URL,    :string, sample_value: "redis://localhost:6379"
```

So we have an example value for `REDIS_URL` (where we would now use a default-value) and the database-variable that we expect to differ between setups and so it only has a description/hint.

A user should get the instruction to copy `env.sample` to `env`, provide the values and source it.

I see the following benefits:
* `ENVied.require` becomes simpler: check if env-values are present and coercible. No more evalling of default-blocks, checking whether defaults are enabled etc.
* make setting the env-variables an explicit step for the user - no way around this as this is the way that the app is configured. _ENVied won't be a possible source of values_.
* provide defaults/hints for the tools that help the user set the environment - and more importantly, for the tools that the user already knows to set the environment.
* an example shell-file can also be used as template in environments where you won't/should not use defaults
* you can provide default-values for `ENV['VARIABLE']` not only for `ENVied.VARIABLE`. The latter is only used by the code you write. The former is also used by dependencies (e.g. `RAILS_ENV`, `REDIS_URL` etc.)

## planning

I reckon fixing this before v1.0 might require some iterations/real-life-feedback (and so might delay that release). Though I think it's worth it as default-values are not 1.0-worthy.

## resources

A tool I now use for years to get my environment right is https://github.com/direnv/direnv. Highly recommended. It targets different shells with just bash-syntax - so it would help us not go overboard with all kinds of shell-specific-generators.

Thoughts welcome!

**Comment by javierjulio** [comment]
This is a lot to take in. I see what you mean though. I'm going to go over this again. I like the benefits. What we create would have to be able to regenerate that sample env file over and over too. I like that we have parity with ENV as well, we should as your point on setting a default only allows `ENVied.A`, but not `ENV['A']` so dependencies can't use it which isn't good.

In the meantime though since we have other smaller useful changes that aren't breaking like this would, I think then we should do an earlier minor release as those changes don't need to wait for a 1.0.

**Comment by eval** [comment]
> What we create would have to be able to regenerate that sample env file over and over too.

Good point. Let's assume that file is fully controlled by ENVied with a warning on top to prevent users from editing it.

**Comment by javierjulio** [comment]
As an example, if you were in a Rails app, how would you go about sourcing the file containing exports? Since that would have to happen separately and before Envied checks and requires all variables are set.

**Comment by eval** [comment]
direnv loads and unloads automatically on entering/leaving a folder. Without direnv a `source .envrc` in bash would suffice. All should be done outside of your Rails-app.

**Comment by Tonkpils** [comment]
I just found this gem and I think the idea behind it is really neat. 

As a side idea to tackle this default issue:

What about removing defaults all together and encouraging users to use something like https://github.com/bkeepers/dotenv. That way, there's less complexity on this gem and allows users to use an existing tool for this and not adding the whole default sample file generation. 

If it comes down to it, you could even integrate dotenv to handle automatic sourcing of the file within this gem as an opt-in though at that point it'd be the same as asking the user to integrate it themselves.

**Comment by eval** [comment]
I think this is still worth to tackle before 1.0. And I think the suggestion of @Tonkpils is spot on: default values are a orthogonal problem and are better solved via dotenv/direnv. Having logic in this gem (and annotations/config in Envfile) to help support generating files for dotenv/direnv is too much and its use quite limited as subsequent exports will clash with existing contents of `.envrc`.

Suggestions:
- remove defaults (via lightweight #36, probably nice to have a minor/patch-release with deprecation-warning)
- document having `.envrc` in a project (and handling load via dotenv)

WDYT @javierjulio?

**Comment by javierjulio** [comment]
Regarding removing the support for defaults, to sum it up I do think that we should do it but I think its best as a standalone change in a single release. Working with a team, they think most of ENVied as setting defaults so its a big change. Whether that's v1 or v2, etc. I don't know.

More importantly though, how would an implementation look and work using either dotenv or direnv or both?

As of now ENVied requires that all listed variables are present. With this removal could ENVied support a case of supporting optional variables?

With defaults removed, we wouldn't have to worry about whether we are getting strings or not since all the values are being coerced from a single source: `ENV` right?

**Comment by javierjulio** [comment]
Regarding removing the support for defaults, to sum it up I do think that we should do it but I think its best as a standalone change in a single release. Working with a team, they think most of ENVied as setting defaults so its a big change. Whether that's v1 or v2, etc. I don't know.

More importantly though, how would an implementation look and work using either dotenv or direnv or both?

As of now ENVied requires that all listed variables are present. With this removal could ENVied support a case of supporting optional variables?

With defaults removed, we wouldn't have to worry about whether we are getting strings or not since all the values are being coerced from a single source: `ENV` right? 

And if we use something like dotenv when and how do we load the defaults?

**Comment by javierjulio** [comment]
Another thing, if we go this route or something similar, I do think **we should have a release where we enforce that default values are all in string format** as we previously had ([commit](https://github.com/eval/envied/blob/53549660c2e4c9424fe0e2f8ec02046268ee8127/lib/envied/variable.rb#L10-L12)). This way it transitions anyone that has mixed type default values to all be strings, just like it would be as the result of a plain ENV variable. 

We'd have that for one major release and then in another major release when we address this case about defaults, its easier for us and users to transition because their default values are already in ENV form meaning that the value just gets dropped into a `.envrc` (or any other file) as is since the value is already in the right format.
